version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks
      - PORT=4000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    build:
      context: ./test-app
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4000
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./test-app:/app
      - /app/node_modules

volumes:
  db_data:


